### ISSUE TITLE
Multidex issue on espresso test run

### ISSUE THREAD

**Issue by originx** [originx/Gradle_troubles_android_enteprise#5]
`./gradlew spoonGermanyDebugAndroidTest`
to see our primary issue

```

core:transformDexArchiveWithDexMergerForGermanyDebugAndroidTest
Dex: The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
    
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:512)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:272)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:521)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:194)
        at com.android.builder.dexing.DexArchiveMergerCallable.mergeDexes(DexArchiveMergerCallable.java:67)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:54)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
:core:transformDexArchiveWithDexMergerForGermanyDebugAndroidTest FAILED

FAILURE: Build failed with an exception.
```

**Comment by originx** [comment]
https://issuetracker.google.com/issues/37324038

is opened

**Comment by originx** [comment]
Comment from google dev:
"
https://android-review.googlesource.com/#/c/276561/  allows native multidex test apks. Legacy multidex tested app still requires mono-dex test apk. It should be released in the next canary release of the plugin. 
2.4-0-alpha 8 or higher
 The change is part of the multidex support library, and that is released as part of the SDK (not plugin nor Android Studio). Once the change is in, I will work on adding the support in the plugin. Unfortunately, I cannot provide any ETA. The owner of that change is aware of this bug (it is referenced from an internal bug report that is assigned to him)
"
